// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCxzRtnk384ubsa8B2xy8JbClifeX4b1Y',
    appId: '1:734390645092:web:82b245e4fe26aa52920a71',
    messagingSenderId: '734390645092',
    projectId: 'finnexus-52cb0',
    authDomain: 'finnexus-52cb0.firebaseapp.com',
    storageBucket: 'finnexus-52cb0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeuBgMOC2T-YlJU7lkCJoGcLLI1JkQ19o',
    appId: '1:734390645092:android:6be6b19f13a39135920a71',
    messagingSenderId: '734390645092',
    projectId: 'finnexus-52cb0',
    storageBucket: 'finnexus-52cb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4mUej12FYMjDg5X1b8QkrtDacqwneeTU',
    appId: '1:734390645092:ios:693240be705969ed920a71',
    messagingSenderId: '734390645092',
    projectId: 'finnexus-52cb0',
    storageBucket: 'finnexus-52cb0.firebasestorage.app',
    iosBundleId: 'com.example.finnexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4mUej12FYMjDg5X1b8QkrtDacqwneeTU',
    appId: '1:734390645092:ios:693240be705969ed920a71',
    messagingSenderId: '734390645092',
    projectId: 'finnexus-52cb0',
    storageBucket: 'finnexus-52cb0.firebasestorage.app',
    iosBundleId: 'com.example.finnexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCxzRtnk384ubsa8B2xy8JbClifeX4b1Y',
    appId: '1:734390645092:web:dce3c8469bb12d25920a71',
    messagingSenderId: '734390645092',
    projectId: 'finnexus-52cb0',
    authDomain: 'finnexus-52cb0.firebaseapp.com',
    storageBucket: 'finnexus-52cb0.firebasestorage.app',
  );
}
